name: bepbuddy
description: A Flutter app for monthly and all-time invoice management
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core UI
  cupertino_icons: ^1.0.8
  provider: ^6.1.5

  # Persistence & State
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.2.0
  uuid: ^4.5.1

  # File I/O & Attachments
  file_selector: ^0.9.5
  image_picker: ^1.1.2
  path: ^1.8.4
  path_provider: ^2.1.5

  # HTTP & MIME
  http: ^1.4.0
  mime: ^1.0.6
  url_launcher: ^6.3.1

  # Formatting & Opening Files
  intl: ^0.18.1
  open_file: ^3.2.1

  # PDF generation & printing
  pdf: ^3.10.1
  printing: ^5.14.2

  # Sharing
  share_plus: ^11.0.0
  share_handler_android:
    path: ./plugins/share_handler_android
  share_handler_platform_interface: ^0.0.6

  # ZIP packaging
  archive: ^3.6.1
  firebase_core: ^3.13.1
  firebase_storage: ^12.4.6
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # App-icon generator
  flutter_launcher_icons: ^0.14.3

dependency_overrides:
  image_picker_macos: ^0.2.1+2

flutter:
  uses-material-design: true

# <—— Removed the assets: section entirely
# If in the future you add real asset files, list them here:
# flutter:
#   assets:
#     - assets/icon/app_icon.png

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png
