// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEBm_1E6-T00ZeHn1F59E8AjHwvmvdXyI',
    appId: '1:271352501327:web:1dcd8879b11ab481c0863a',
    messagingSenderId: '271352501327',
    projectId: 'bepbuddy',
    authDomain: 'bepbuddy.firebaseapp.com',
    storageBucket: 'bepbuddy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyAFOTbGpBn4LQA6wxF2eWLNNYtUVFdWY',
    appId: '1:271352501327:android:1083680805093e06c0863a',
    messagingSenderId: '271352501327',
    projectId: 'bepbuddy',
    storageBucket: 'bepbuddy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCazG9ZXB9gEYXSMZ3jnZ3VUm1Fc9DDIdU',
    appId: '1:271352501327:ios:7bd712c0771eb537c0863a',
    messagingSenderId: '271352501327',
    projectId: 'bepbuddy',
    storageBucket: 'bepbuddy.firebasestorage.app',
    iosBundleId: 'com.madlabz.bepbuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCazG9ZXB9gEYXSMZ3jnZ3VUm1Fc9DDIdU',
    appId: '1:271352501327:ios:7bd712c0771eb537c0863a',
    messagingSenderId: '271352501327',
    projectId: 'bepbuddy',
    storageBucket: 'bepbuddy.firebasestorage.app',
    iosBundleId: 'com.madlabz.bepbuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEBm_1E6-T00ZeHn1F59E8AjHwvmvdXyI',
    appId: '1:271352501327:web:c72300360d5d71e6c0863a',
    messagingSenderId: '271352501327',
    projectId: 'bepbuddy',
    authDomain: 'bepbuddy.firebaseapp.com',
    storageBucket: 'bepbuddy.firebasestorage.app',
  );

}